package ru.ifmo.se.lab3;

// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.openqa.selenium.support.ui.ExpectedConditions.textToBePresentInElementLocated;

public class DistanceMeasurementTest extends BaseTest {

    private static final long DEFAULT_PAGE_LOAD_WAITING_TIME = 5000L;
    private static final int DEFAULT_TIMEOUT = 5;

    @Test
    public void distanceMeasurement() throws InterruptedException {
        for (WebDriver driver : drivers) {
            driver.get("http://wikimapia.org/");
            driver.manage().timeouts().implicitlyWait(DEFAULT_PAGE_LOAD_WAITING_TIME, TimeUnit.MILLISECONDS);
            driver.findElement(By.xpath("//div[11]/div/div/span")).click();
            WebDriverWait wait = new WebDriverWait(driver, DEFAULT_TIMEOUT);
            wait.until(textToBePresentInElementLocated(By.xpath("//em"), "0"));
            assertEquals("0", driver.findElement(By.xpath("//em")).getText());
            driver.manage().timeouts().implicitlyWait(DEFAULT_PAGE_LOAD_WAITING_TIME, TimeUnit.MILLISECONDS);
            Actions actions = new Actions(driver);
            WebElement tile11 = driver.findElement(By.xpath("//*[@id='tile-11']"));
            actions.moveToElement(tile11).click().perform();
            actions.click().perform();
            WebElement tile14 = driver.findElement(By.xpath("//*[@id='tile-12']"));
            actions.moveToElement(tile14).click().perform();;
            actions.click().perform();
            String firstStep = driver.findElement(By.xpath("//em")).getText();
            assertTrue(!firstStep.equals("0") && !firstStep.equals(""));
            WebElement tile7 =  driver.findElement(By.xpath("//*[@id='tile-7']"));
            actions.moveToElement(tile7).click().perform();
            actions.click().perform();
            String secondStep = driver.findElement(By.xpath("//em")).getText();
            assertTrue(!firstStep.equals(secondStep) && !secondStep.equals(""));
            actions.contextClick().perform();
            driver.findElement(By.xpath("//a/span")).click();
            String thirdStep = driver.findElement(By.xpath("//em")).getText();
            assertTrue(!thirdStep.equals(secondStep) && thirdStep.equals(firstStep));
            driver.findElement(By.xpath("//div[7]/div/span")).click();
        }
    }
}
