package ru.ifmo.se.lab3;

// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import static org.junit.Assert.assertEquals;

public class LangTest extends BaseTest {

    @Test
    public void lang() {
        for (WebDriver driver : drivers) {
            driver.get("http://wikimapia.org/");
            WebElement element = driver.findElement(By.linkText("RU"));
            Actions actions = new Actions(driver);
            actions.moveToElement(element).perform();
            driver.findElement(By.xpath("//li[4]/ul/li/a/span")).click();
            assertEquals("Login", driver.findElement(By.xpath("//div/ul/li[3]/a/span[2]")).getText());
            element = driver.findElement(By.linkText("EN"));
            actions.moveToElement(element).perform();
            driver.findElement(By.xpath("//li[4]/ul/li[2]/a/span")).click();
            assertEquals("Войти", driver.findElement(By.xpath("//div/ul/li[3]/a/span[2]")).getText());
        }
    }
}
