package ru.ifmo.se.lab3;

// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.junit.Assert.assertEquals;
import static org.openqa.selenium.support.ui.ExpectedConditions.frameToBeAvailableAndSwitchToIt;

public class LoginTest extends BaseTest {
    private static final int DEFAULT_TIMEOUT = 5;
    @Test
    public void login() {
        for (WebDriver driver : drivers) {
            driver.get("http://wikimapia.org/");
            WebElement element = driver.findElement(By.xpath("//div/ul/li[3]/a/span[2]"));
            Actions actions = new Actions(driver);
            actions.moveToElement(element).perform();
            driver.findElement(By.xpath("//li[3]/ul/li/a/span[2]")).click();
            WebDriverWait wait = new WebDriverWait(driver, DEFAULT_TIMEOUT);
            wait.until(frameToBeAvailableAndSwitchToIt(By.xpath("//iframe[contains(@src,'login')]")));
            driver.findElement(By.xpath("//div[2]/input")).click();
            assertEquals("rgba(185, 74, 72, 1)", driver.findElement(By.xpath("//label[@for='username']")).getCssValue("color"));
            driver.switchTo().defaultContent();
            driver.findElement(By.xpath("//div[16]/div/span")).click();
        }
    }
}
