package ru.ifmo.se.lab3;

// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.junit.Assert.assertEquals;
import static org.openqa.selenium.support.ui.ExpectedConditions.textToBePresentInElementLocated;

public class MapChangeTest extends BaseTest {
    private static final int DEFAULT_TIMEOUT = 5;
    @Test
    public void mapChange() {
        for (WebDriver driver : drivers) {
            driver.get("http://wikimapia.org/");
            driver.findElement(By.xpath("//div[4]/div/div/div")).click();
            driver.findElement(By.xpath("//div[10]")).click();
            WebDriverWait wait = new WebDriverWait(driver, DEFAULT_TIMEOUT);
            wait.until(textToBePresentInElementLocated(By.xpath("//div[4]/div/div/div"), "Гибрид Яндекса"));
            assertEquals("Гибрид Яндекса", driver.findElement(By.xpath("//div[4]/div/div/div")).getText());
            driver.findElement(By.xpath("//div[4]/div/div/div")).click();
            driver.findElement(By.xpath("//div[4]/div[2]/div/div[2]")).click();
            wait.until(textToBePresentInElementLocated(By.xpath("//div[4]/div/div/div"), "Карта Викимапии"));
            assertEquals("Карта Викимапии", driver.findElement(By.xpath("//div[4]/div/div/div")).getText());
        }
    }
}
