package ru.ifmo.se.lab3;

// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import static org.junit.Assert.assertTrue;

public class ZoomTest extends BaseTest {

    private static final double SINGLE_ZOOM_UNIT = 9.0;
    private static final double SLIDER_MIN_TOP = 23.0;

    @Test
    public void zoom() {
        for (WebDriver driver : drivers) {
            double initialTop, resultTop;
            int i = 0;
            driver.get("http://wikimapia.org/");
            initialTop = Double.parseDouble(
                    driver.findElement(By.xpath("//div[3]/div[5]"))
                            .getCssValue("top").replaceAll("px", "")
            );
            do {
                i++;
                driver.findElement(By.xpath("//div[3]/div[4]")).click();
                resultTop = Double.parseDouble(
                        driver.findElement(By.xpath("//div[3]/div[5]"))
                                .getCssValue("top").replaceAll("px", "")
                );
                double expectedDiff = SINGLE_ZOOM_UNIT * i;
                assertTrue(expectedDiff == initialTop - resultTop || resultTop == SLIDER_MIN_TOP);
            } while (resultTop > SLIDER_MIN_TOP);
        }
    }
}
